/**:
  ros__parameters:
    ## image resolution
    
    image_size_x: 1280
    image_size_y: 720

    
    ## camera intrinsics

    focal_x: 531.5750
    focal_y: 531.3700
    center_x: 643.3700
    center_y: 356.9830
  
    ## camera extrinsics, with respect to base-link
    
    # euler rotations to base-link in degrees
    rotation_x: 0.0
    rotation_y: 0.0
    rotation_z: 0.0
    # translations from base-link
    translation_x: 0.5
    translation_y: 0.0
    translation_z: -1.5